######################################################################
# Automatically generated by qmake (3.0) Sat Dec 12 22:23:18 2015
######################################################################

TEMPLATE = app
TARGET = warning-viewer
INCLUDEPATH += .

# Input
SOURCES += main.cpp mainwindow.cpp warningmodel.cpp warningproxymodel.cpp
HEADERS += mainwindow.h warningmodel.h warningproxymodel.h

FORMS += mainwindow.ui

CONFIG += c++11
QT += widgets
